# Generated by Django 4.2.8 on 2024-06-09 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("website", "0004_remove_usuarios_idempleado_empleados_idusuario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriasArticulos",
            fields=[
                (
                    "IdCategoria",
                    models.CharField(db_index=True, max_length=8, unique=True),
                ),
                (
                    "IdElementoCategoria",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("DescripcionCategoria", models.CharField(max_length=50)),
                ("SubCategoria", models.CharField(max_length=8, null=True)),
                ("CondicionExistenciaCategoria", models.CharField(max_length=1)),
                (
                    "SlugCategoria",
                    models.SlugField(blank=True, max_length=200, unique=True),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaCategorias",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioCategorias",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "CategoriaArticulos",
                "verbose_name_plural": "CategoriasArticulos",
                "db_table": "CategoriasArticulos",
                "ordering": ("-IdCategoria",),
                "unique_together": {("IdCategoria", "SlugCategoria")},
            },
        ),
        migrations.CreateModel(
            name="MarcasArticulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdCategoria", models.CharField(db_index=True, max_length=8)),
                ("IdMarca", models.IntegerField(db_index=True, unique=True)),
                ("DescripcionMarca", models.CharField(max_length=50)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaMarcasArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioMarcasArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "MarcaArticulos",
                "verbose_name_plural": "MarcasArticulos",
                "db_table": "MarcasArticulos",
                "ordering": ("-IdMarca",),
                "unique_together": {("IdCategoria", "IdMarca")},
                "index_together": {("IdCategoria", "IdMarca")},
            },
        ),
        migrations.CreateModel(
            name="PresentacionesArticulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdCategoria", models.CharField(db_index=True, max_length=8)),
                ("IdPresentacion", models.IntegerField(db_index=True, unique=True)),
                ("DescripcionPresentacion", models.CharField(max_length=50)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaPresentacionesArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioPresentacionesArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "PresentacionArticulos",
                "verbose_name_plural": "PresentacionesArticulos",
                "db_table": "PresentacionesArticulos",
                "ordering": ("-IdPresentacion",),
                "unique_together": {("IdCategoria", "IdPresentacion")},
                "index_together": {("IdCategoria", "IdPresentacion")},
            },
        ),
        migrations.CreateModel(
            name="UnidadesSAT",
            fields=[
                (
                    "IdUnidadSAT",
                    models.CharField(
                        max_length=3, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("NombreUnidadSAT", models.CharField(max_length=128)),
                ("DescripcionUnidadSAT", models.CharField(max_length=640)),
                ("NotaUnidadSAT", models.CharField(max_length=256)),
                ("SimboloUnidadSAT", models.CharField(max_length=30)),
                ("ValorSistema", models.CharField(max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaUnidadesSAT",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioUnidadesSAT",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "UnidadSAT",
                "verbose_name_plural": "UnidadesSAT",
                "db_table": "UnidadesSAT",
                "ordering": ("-IdUnidadSAT",),
            },
        ),
        migrations.CreateModel(
            name="ProductosSAT",
            fields=[
                (
                    "IdProductoSAT",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("DescripcionProductoSAT", models.CharField(max_length=256)),
                (
                    "IncluirIVATrasladoProductoSAT",
                    models.CharField(default="O", max_length=1),
                ),
                (
                    "IncluirIEPSRTrasladoProductoSAT",
                    models.CharField(default="N", max_length=1),
                ),
                ("ComplementoProductoSAT", models.IntegerField(null=True)),
                (
                    "IncluidComplementoProductoSAT",
                    models.CharField(default="N", max_length=1),
                ),
                (
                    "CondicionMaterialPeligrosoProductoSAT",
                    models.CharField(default="0", max_length=1),
                ),
                (
                    "ClaveMaterialPeligrosoProductoSAT",
                    models.CharField(max_length=5, null=True),
                ),
                ("ValorSistema", models.CharField(default="S", max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaProductosSAT",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioProductosSAT",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductoSAT",
                "verbose_name_plural": ("ProductosSAT",),
                "db_table": "ProductosSAT",
                "ordering": ("-IdProductoSAT",),
            },
        ),
        migrations.CreateModel(
            name="Articulos",
            fields=[
                ("IdArticulo", models.IntegerField(db_index=True, unique=True)),
                ("NombreArticulo", models.CharField(max_length=256)),
                ("EtiquetaArticulo", models.CharField(max_length=15)),
                ("UPCArticulo", models.CharField(max_length=13, null=True)),
                ("DescripcionArticulo", models.CharField(max_length=128)),
                ("ModeloArticulo", models.CharField(max_length=40)),
                ("MedidaArticulo", models.CharField(max_length=5)),
                ("UnidadMedidaArticulo", models.IntegerField(null=True)),
                ("FabricanteArticulo", models.IntegerField(null=True)),
                ("ClaseArticulo", models.IntegerField()),
                ("ProveedorPrimarioArticulo", models.IntegerField()),
                ("CotizacionesArticulo", models.IntegerField()),
                ("ProcedenciaArticulo", models.CharField(max_length=1)),
                (
                    "ArancelArticulo",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "MargenArticulo",
                    models.DecimalField(decimal_places=4, max_digits=11),
                ),
                ("UnidadExistenciaArticulo", models.IntegerField()),
                ("UnidadesEntradaArticulo", models.IntegerField()),
                ("UnidadesSalidaArticulo", models.IntegerField()),
                (
                    "FactorEntradaArticulo",
                    models.DecimalField(decimal_places=5, max_digits=16),
                ),
                (
                    "FactorSalidaArticulo",
                    models.DecimalField(decimal_places=5, max_digits=16),
                ),
                (
                    "FactorEmbalajeArticulo",
                    models.DecimalField(decimal_places=5, max_digits=16),
                ),
                ("CantidadUnidadesArticulo", models.IntegerField()),
                (
                    "FactorLitrosArticulo",
                    models.DecimalField(decimal_places=5, max_digits=16),
                ),
                ("AnchoArticulo", models.DecimalField(decimal_places=3, max_digits=10)),
                ("AltoArticulo", models.DecimalField(decimal_places=3, max_digits=10)),
                ("FondoArticulo", models.DecimalField(decimal_places=3, max_digits=10)),
                ("PesoArticulo", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "ImagenArticulo",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos/%Y/%m/%d"
                    ),
                ),
                ("FormatoImagenArticulo", models.CharField(max_length=50, null=True)),
                ("NombreImagenArticulo", models.CharField(max_length=128, null=True)),
                ("CondicionReordenArticulo", models.CharField(max_length=1)),
                ("CondicionFraccionesArticulo", models.CharField(max_length=1)),
                ("CondicionExistenciaNegativaArticulo", models.CharField(max_length=1)),
                ("CondicionEtiquetaArticulo", models.CharField(max_length=1)),
                ("CondicionMantenimientoArticulo", models.CharField(max_length=1)),
                ("CondicionPrecioVentaArticulo", models.CharField(max_length=1)),
                ("CondicionPrecioCompraArticulo", models.CharField(max_length=1)),
                ("Garantia1Articulo", models.IntegerField()),
                ("Garantia2Articulo", models.IntegerField()),
                ("CondicionReemplazoArticulo", models.CharField(max_length=1)),
                ("CaducidadArticulo", models.DateField()),
                ("OperacionSATArticulo", models.IntegerField(null=True)),
                (
                    "IdElementoArticulo",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "SlugArticulo",
                    models.SlugField(blank=True, max_length=200, unique=True),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        db_column="IdCategoria",
                        max_length=8,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categoriasArticulos",
                        to="store.categoriasarticulos",
                        to_field="IdCategoria",
                    ),
                ),
                (
                    "IdProductoSATArticulo",
                    models.ForeignKey(
                        db_column="IdProductoSATArticulo",
                        max_length=8,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productosSAT",
                        to="store.productossat",
                    ),
                ),
                (
                    "IdUnidadSATArticulo",
                    models.ForeignKey(
                        db_column="IdUnidadSATArticulo",
                        max_length=3,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidadesSAT",
                        to="store.unidadessat",
                    ),
                ),
                (
                    "MarcaArticulo",
                    models.ForeignKey(
                        db_column="MarcaArticulo",
                        max_length=3,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marcas",
                        to="store.marcasarticulos",
                        to_field="IdMarca",
                    ),
                ),
                (
                    "PresentacionArticulo",
                    models.ForeignKey(
                        db_column="PresentacionArticulo",
                        max_length=3,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presentaciones",
                        to="store.presentacionesarticulos",
                        to_field="IdPresentacion",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Articulo",
                "verbose_name_plural": "Articulos",
                "db_table": "Articulos",
                "ordering": ("-IdCategoria",),
                "unique_together": {("IdCategoria", "IdArticulo")},
                "index_together": {("IdCategoria", "IdArticulo")},
            },
        ),
        migrations.CreateModel(
            name="Almacenes",
            fields=[
                (
                    "IdAlmacen",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("NombreAlmacen", models.CharField(max_length=50)),
                ("EtiquetaAlmacen", models.CharField(max_length=15)),
                ("SubAlmacen", models.CharField(max_length=10)),
                ("ResponsableAlmacen", models.CharField(max_length=10)),
                ("SupervisorAlmacen", models.CharField(max_length=10, null=True)),
                (
                    "SuperficieAlmacen",
                    models.DecimalField(decimal_places=2, max_digits=13),
                ),
                ("FechaAperturaAlmacen", models.DateField()),
                ("FechaUltimoInventarioAlmacen", models.DateField()),
                ("HoraUltimoInventarioAlmacen", models.TimeField()),
                ("FechaPenultimoInventarioAlmacen", models.DateField()),
                ("HoraPenultimoInventarioAlmacen", models.TimeField()),
                (
                    "IdElementoAlmacen",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaAlmacenes",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioAlmacenes",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Almacen",
                "verbose_name_plural": "Almacenes",
                "db_table": "Almacenes",
                "ordering": ("-IdAlmacen",),
            },
        ),
        migrations.CreateModel(
            name="PresentacionesCategorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.categoriasarticulos",
                    ),
                ),
                (
                    "IdPresentacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.presentacionesarticulos",
                    ),
                ),
            ],
            options={
                "unique_together": {("IdCategoria", "IdPresentacion")},
            },
        ),
        migrations.CreateModel(
            name="MarcasCategorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.categoriasarticulos",
                    ),
                ),
                (
                    "IdMarca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.marcasarticulos",
                    ),
                ),
            ],
            options={
                "unique_together": {("IdCategoria", "IdMarca")},
            },
        ),
        migrations.CreateModel(
            name="AlmacenArticulos",
            fields=[
                (
                    "MaximoArticuloAlmacen",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "MinimoArtiuloAlmacen",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "ReordenArticuloAlmacen",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("UbicacionArticuloAlmacen", models.CharField(max_length=6)),
                ("ProveedorPrimarioArticuloAlmacen", models.IntegerField(null=True)),
                (
                    "IdElementoProveedor",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "IdAlmacen",
                    models.ForeignKey(
                        db_column="IdAlmacen",
                        max_length=10,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="almacenesArticulos",
                        to="store.almacenes",
                        to_field="IdAlmacen",
                    ),
                ),
                (
                    "IdArticulo",
                    models.ForeignKey(
                        db_column="IdArticulo",
                        max_length=10,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulosAlmacenArticulos",
                        to="store.articulos",
                        to_field="IdArticulo",
                    ),
                ),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        db_column="IdCategoria",
                        max_length=8,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categoriasAlmacenArticulos",
                        to="store.categoriasarticulos",
                        to_field="IdCategoria",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaAlmacen",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioAlmacen",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlmacenArticulo",
                "verbose_name_plural": "AlmacenArticulos",
                "db_table": "AlmacenArticulos",
                "ordering": ("-IdAlmacen",),
                "unique_together": {("IdAlmacen", "IdCategoria", "IdArticulo")},
                "index_together": {("IdAlmacen", "IdCategoria", "IdArticulo")},
            },
        ),
        migrations.CreateModel(
            name="AlmacenArticuloExistencias",
            fields=[
                ("IdEstadoExistencia", models.IntegerField(db_index=True)),
                ("EjercicioExistenciasArticulo", models.IntegerField(db_index=True)),
                (
                    "InicialExistenciasArticulo",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo01",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo02",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo03",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo04",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo05",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo06",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo07",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo08",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo09",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo10",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo11",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "EntradasExistenciasArticulo12",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo01",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo02",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo03",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo04",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo05",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo06",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo07",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo08",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo09",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo10",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo11",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "SalidasExistenciasArticulo12",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "IdElementoAlmacenArticuloExistencia",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "IdAlmacen",
                    models.ForeignKey(
                        db_column="IdAlmacen",
                        max_length=10,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="almacenesArticuloExistencias",
                        to="store.almacenes",
                        to_field="IdAlmacen",
                    ),
                ),
                (
                    "IdArticulo",
                    models.ForeignKey(
                        db_column="IdArticulo",
                        max_length=10,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulosAlmacenArticuloExistencias",
                        to="store.articulos",
                        to_field="IdArticulo",
                    ),
                ),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        db_column="IdCategoria",
                        max_length=8,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categoriasAlmacenArticuloExistencias",
                        to="store.categoriasarticulos",
                        to_field="IdCategoria",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaExistencias",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioExistencias",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlmacenArticuloExistencia",
                "verbose_name_plural": "AlmacenArticuloExistencias",
                "db_table": "AlmacenArticuloExistencias",
                "ordering": ["IdAlmacen", "IdCategoria", "IdArticulo"],
                "unique_together": {
                    (
                        "IdAlmacen",
                        "IdCategoria",
                        "IdArticulo",
                        "IdEstadoExistencia",
                        "EjercicioExistenciasArticulo",
                    )
                },
                "index_together": {
                    (
                        "IdAlmacen",
                        "IdCategoria",
                        "IdArticulo",
                        "IdEstadoExistencia",
                        "EjercicioExistenciasArticulo",
                    )
                },
            },
        ),
    ]
