# Generated by Django 4.2.8 on 2024-06-07 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="almacenarticuloexistencias",
            options={
                "ordering": ["-IdAlmacen", "IdCategoria", "IdArticulo"],
                "verbose_name": "AlmacenArticuloExistencia",
                "verbose_name_plural": "AlmacenArticuloExistencias",
            },
        ),
        migrations.AlterModelTable(
            name="almacenarticuloexistencias",
            table="AlmacenArticuloExistencias",
        ),
    ]
