# Generated by Django 4.2.8 on 2024-06-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_usuarios_idempleado_empleados_idusuario_and_more"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Divisas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IdDivisa",
                    models.CharField(db_index=True, max_length=3, unique=True),
                ),
                ("NombreDivisa", models.CharField(max_length=40)),
                ("EtiquetaDivisa", models.CharField(max_length=15)),
                ("SimboloDivisa", models.CharField(max_length=3)),
                (
                    "BanderaDivisa",
                    models.ImageField(
                        blank=True, null=True, upload_to="divisas/%Y/%m/%d"
                    ),
                ),
                ("FormatoBanderaDivisa", models.CharField(max_length=50, null=True)),
                ("NombreBanderaDivisa", models.CharField(max_length=128, null=True)),
                ("PorDefectoDivisa", models.CharField(max_length=1)),
                ("ValorSistema", models.CharField(default="S", max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaDivisas",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioDivisas",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Divisa",
                "verbose_name_plural": "Divisas",
                "db_table": "Divisas",
                "ordering": ("-IdDivisa",),
            },
        ),
        migrations.CreateModel(
            name="CostosArticulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FechaCosto", models.DateField(db_index=True)),
                ("CostoUnitario", models.DecimalField(decimal_places=6, max_digits=22)),
                (
                    "TipoCambioCosto",
                    models.DecimalField(decimal_places=6, max_digits=22),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "DivisaCosto",
                    models.ForeignKey(
                        db_column="IdDivisa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="divisasCostosArticulos",
                        to="store.divisas",
                    ),
                ),
                (
                    "IdArticulo",
                    models.ForeignKey(
                        db_column="IdArticulo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulosCostosArticulos",
                        to="store.articulos",
                    ),
                ),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        db_column="IdCategoria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categoriasCostosArticulos",
                        to="store.categoriasarticulos",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaCostosArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioCostosArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "CostosArticulo",
                "verbose_name_plural": "CostosArticulos",
                "db_table": "CostosArticulos",
                "unique_together": {("IdCategoria", "IdArticulo", "FechaCosto")},
                "index_together": {("IdCategoria", "IdArticulo", "FechaCosto")},
            },
        ),
    ]
