# Generated by Django 4.2.8 on 2024-06-07 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_almacenarticuloexistencias_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="almacenarticuloexistencias",
            options={
                "ordering": ["IdAlmacen", "IdCategoria", "IdArticulo"],
                "verbose_name": "AlmacenArticuloExistencia",
                "verbose_name_plural": "AlmacenArticuloExistencias",
            },
        ),
    ]
