# Generated by Django 4.2.8 on 2024-06-14 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_usuarios_idempleado_empleados_idusuario_and_more"),
        ("store", "0002_divisas_costosarticulos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriasarticulos",
            name="SubCategoria",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="categoriasarticulos",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaCategorias",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="categoriasarticulos",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioCategorias",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
    ]
