# Generated by Django 4.2.8 on 2024-06-07 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_almacenarticuloexistencias_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="almacenarticulos",
            table="AlmacenArticulos",
        ),
        migrations.AlterModelTable(
            name="almacenes",
            table="Almacenes",
        ),
        migrations.AlterModelTable(
            name="articulos",
            table="Articulos",
        ),
        migrations.AlterModelTable(
            name="categoriasarticulos",
            table="CategoriasArticulos",
        ),
        migrations.AlterModelTable(
            name="marcasarticulos",
            table="MarcasArticulos",
        ),
        migrations.AlterModelTable(
            name="presentacionesarticulos",
            table="PresentacionesArticulos",
        ),
        migrations.AlterModelTable(
            name="productossat",
            table="ProductosSAT",
        ),
        migrations.AlterModelTable(
            name="unidadessat",
            table="UnidadesSAT",
        ),
    ]
