# Generated by Django 4.2.8 on 2024-06-14 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_categoriasarticulos_subcategoria_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriasarticulos",
            options={
                "ordering": ("IdElementoCategoria", "IdCategoria"),
                "verbose_name": "CategoriaArticulos",
                "verbose_name_plural": "CategoriasArticulos",
            },
        ),
    ]
