# Generated by Django 4.2.8 on 2024-06-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_categoriasarticulos_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marcasarticulos",
            name="IdCategoria",
            field=models.ManyToManyField(
                db_column="IdCategoria",
                db_index=True,
                through="store.MarcasCategorias",
                to="store.categoriasarticulos",
            ),
        ),
        migrations.AlterField(
            model_name="presentacionesarticulos",
            name="IdCategoria",
            field=models.ManyToManyField(
                db_column="IdCategoria",
                db_index=True,
                through="store.PresentacionesCategorias",
                to="store.categoriasarticulos",
            ),
        ),
    ]
