# Generated by Django 4.2.8 on 2024-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_marcasarticulos_idcategoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marcasarticulos",
            name="IdCategoria",
            field=models.ManyToManyField(
                db_index=True,
                through="store.MarcasCategorias",
                to="store.categoriasarticulos",
            ),
        ),
        migrations.AlterField(
            model_name="presentacionesarticulos",
            name="IdCategoria",
            field=models.ManyToManyField(
                db_index=True,
                through="store.PresentacionesCategorias",
                to="store.categoriasarticulos",
            ),
        ),
        migrations.AlterModelTable(
            name="marcascategorias",
            table="MarcasCategorias",
        ),
        migrations.AlterModelTable(
            name="presentacionescategorias",
            table="PresentacionesCategorias",
        ),
    ]
