# Generated by Django 4.2.8 on 2024-06-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_usuarios_idempleado_empleados_idusuario_and_more"),
        ("store", "0007_alter_marcasarticulos_idcategoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogos",
            fields=[
                ("IdCatalogo", models.IntegerField(db_index=True)),
                (
                    "ElementoCatalogo",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("ClaseCatalogo", models.CharField(max_length=15)),
                ("PorDefectoCatalogo", models.CharField(max_length=1)),
                ("ValorSistema", models.CharField(max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaCatalogos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioCatalogos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalogo",
                "verbose_name_plural": "Catalogos",
                "db_table": "Catalogos",
                "ordering": ("-IdCatalogo",),
                "unique_together": {("IdCatalogo", "ElementoCatalogo")},
                "index_together": {("IdCatalogo", "ElementoCatalogo")},
            },
        ),
        migrations.CreateModel(
            name="CondicionesPago",
            fields=[
                (
                    "IdCondicionPago",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("DescripcionCondicionPago", models.CharField(max_length=60)),
                ("DiasCreditoCondicionPago", models.IntegerField()),
                (
                    "DescuentoProntoPagoCondicionPago",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("DiasProntoPagoCondicionPago", models.IntegerField()),
                ("ValorSistema", models.CharField(max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaCondicionesPago",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioCondicionesPago",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="articulos",
            name="IdProductoSATArticulo",
            field=models.ForeignKey(
                db_column="IdProductoSATArticulo",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productosSAT",
                to="store.productossat",
            ),
        ),
        migrations.AlterField(
            model_name="articulos",
            name="PresentacionArticulo",
            field=models.ForeignKey(
                db_column="PresentacionArticulo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="presentaciones",
                to="store.presentacionesarticulos",
                to_field="IdPresentacion",
            ),
        ),
        migrations.AlterField(
            model_name="articulos",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaArticulos",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="articulos",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioArticulos",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.CreateModel(
            name="Proveedores",
            fields=[
                ("IdProveedor", models.IntegerField(db_index=True, unique=True)),
                ("RazonSocialProveedor", models.CharField(max_length=128)),
                ("ApellidoPaternoProveedor", models.CharField(max_length=30)),
                ("ApellidoMaternoProveedor", models.CharField(max_length=30)),
                ("NombreProveedor", models.CharField(max_length=30)),
                ("DenominacionProveedor", models.CharField(max_length=30)),
                ("ProcedenciaProveedor", models.CharField(max_length=1)),
                ("ClaseProveedor", models.CharField(max_length=1)),
                ("RFCProveedor", models.CharField(max_length=13)),
                ("CURProveedor", models.CharField(max_length=18)),
                ("FechaAltaProveedor", models.DateField()),
                ("FechaBajaProveedor", models.DateField(blank=True, null=True)),
                ("OpinionSATProveedor", models.CharField(max_length=1)),
                ("FechaOpinionSATProveedor", models.DateField(blank=True, null=True)),
                ("ObservacionesProveedor", models.CharField(max_length=256)),
                ("FechaAperturaProveedor", models.DateField(blank=True, null=True)),
                (
                    "LimiteCreditoProveedor",
                    models.DecimalField(decimal_places=6, max_digits=22),
                ),
                (
                    "PorcentajeAnticipoProveedor",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "DescuentoProveedor",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                ("PlazoEntrega", models.IntegerField()),
                ("CriterioPagoProveedor", models.CharField(max_length=1)),
                ("NumeroCuentaProveedor", models.IntegerField()),
                (
                    "IdElementoProveedor",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "CondicionPagoProveedor",
                    models.ForeignKey(
                        db_column="CondicionPagoProveedor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condicionesPagoProveedores",
                        to="store.condicionespago",
                    ),
                ),
                (
                    "DivisaProveedor",
                    models.ForeignKey(
                        db_column="DivisaProveedor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="divisasProveedores",
                        to="store.divisas",
                        to_field="IdDivisa",
                    ),
                ),
                (
                    "GiroProveedor",
                    models.ForeignKey(
                        db_column="GiroProveedor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="girosProveedores",
                        to="store.catalogos",
                    ),
                ),
                (
                    "SectorProveedor",
                    models.ForeignKey(
                        db_column="SectorProveedor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sectoresProveedores",
                        to="store.catalogos",
                    ),
                ),
                (
                    "TipoProveedor",
                    models.ForeignKey(
                        blank=True,
                        db_column="TipoProveedor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tiposProveedores",
                        to="store.catalogos",
                    ),
                ),
                (
                    "TipoSociedadProveedor",
                    models.ForeignKey(
                        blank=True,
                        db_column="TipoSociedadProveedor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.catalogos",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaProveedores",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioProveedores",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "Proveedores",
                "ordering": ("-IdProveedor",),
            },
        ),
        migrations.CreateModel(
            name="Clientes",
            fields=[
                ("IdCliente", models.IntegerField(db_index=True, unique=True)),
                ("RazonSocialCliente", models.CharField(max_length=128)),
                ("ApellidoPaternoCliente", models.CharField(max_length=30)),
                ("NombreCliente", models.CharField(max_length=30)),
                ("DenominacionCliente", models.CharField(max_length=30)),
                ("ProcedenciaCliente", models.CharField(max_length=1)),
                ("ClaseCliente", models.CharField(max_length=1)),
                ("RFCCliente", models.CharField(max_length=13)),
                ("CURPCliente", models.CharField(max_length=18)),
                ("ObservacionesCliente", models.CharField(max_length=256)),
                ("FechaAltaCliente", models.DateField()),
                ("FechaBajaCliente", models.DateField(blank=True, null=True)),
                ("FechaAperturaCliente", models.DateField(blank=True, null=True)),
                (
                    "LimiteCreditoCliente",
                    models.DecimalField(decimal_places=6, max_digits=22),
                ),
                (
                    "PorcentajeAnticipoCliente",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "DescuentoCliente",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
                ("PlazoEntrega", models.IntegerField()),
                ("CriterioPagoCliente", models.CharField(max_length=1)),
                ("NumeroCuentaCliente", models.IntegerField()),
                (
                    "IdElementoCliente",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "CondicionPagoCliente",
                    models.ForeignKey(
                        db_column="CondicionPagoCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condicionesPagoClientes",
                        to="store.condicionespago",
                    ),
                ),
                (
                    "DivisaCliente",
                    models.ForeignKey(
                        db_column="DivisaCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="divisasClientes",
                        to="store.divisas",
                        to_field="IdDivisa",
                    ),
                ),
                (
                    "GiroCliente",
                    models.ForeignKey(
                        db_column="GiroCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="girosClientes",
                        to="store.catalogos",
                    ),
                ),
                (
                    "SectorCliente",
                    models.ForeignKey(
                        db_column="SectorCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sectoresClientes",
                        to="store.catalogos",
                    ),
                ),
                (
                    "TipoCliente",
                    models.ForeignKey(
                        db_column="TipoCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tiposClientes",
                        to="store.catalogos",
                    ),
                ),
                (
                    "TipoSociedadCliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="TipoSociedadCliente",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.catalogos",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaClientes",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioClientes",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "Clientes",
                "ordering": ("-IdCliente",),
            },
        ),
    ]
