# Generated by Django 4.2.8 on 2024-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_condicionespago_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulos",
            name="FormatoImagenArticulo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="articulos",
            name="NombreImagenArticulo",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
