# Generated by Django 4.2.8 on 2024-06-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_articulos_formatoimagenarticulo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogos",
            name="ClaseCatalogo",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="catalogos",
            name="PorDefectoCatalogo",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="catalogos",
            name="ValorSistema",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
