# Generated by Django 4.2.8 on 2024-06-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_alter_catalogos_clasecatalogo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogos",
            name="EstadoLogico",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="catalogos",
            name="Version",
            field=models.IntegerField(default=0),
        ),
    ]
