# Generated by Django 4.2.8 on 2024-06-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_alter_catalogos_estadologico_alter_catalogos_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogos",
            name="DescripcionCatalogo",
            field=models.CharField(default="", max_length=128),
        ),
    ]
