# Generated by Django 4.2.8 on 2024-06-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_usuarios_idempleado_empleados_idusuario_and_more"),
        ("store", "0013_catalogos_descripcioncatalogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="almacenes",
            name="ResponsableAlmacen",
            field=models.ForeignKey(
                db_column="ResponsableAlmacen",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsablesAlmacenes",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="almacenes",
            name="SupervisorAlmacen",
            field=models.ForeignKey(
                db_column="SupervisorAlmacen",
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supervisoresAlmacenes",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="almacenes",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaAlmacenes",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="almacenes",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioAlmacenes",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
    ]
