# Generated by Django 4.2.8 on 2024-06-27 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_empleados_departamentoempleado_and_more"),
        ("store", "0014_alter_almacenes_responsablealmacen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divisas",
            name="EstadoLogico",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="divisas",
            name="FormatoBanderaDivisa",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="divisas",
            name="NombreBanderaDivisa",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="divisas",
            name="PorDefectoDivisa",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AlterField(
            model_name="divisas",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaDivisas",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="divisas",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioDivisas",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="divisas",
            name="Version",
            field=models.IntegerField(default=0),
        ),
    ]
