# Generated by Django 4.2.8 on 2024-06-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_empleados_departamentoempleado_and_more"),
        ("store", "0015_alter_divisas_estadologico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impuestos",
            fields=[
                (
                    "IdImpuesto",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("DescripcionImpuesto", models.CharField(max_length=60)),
                ("EtiquetaImpuesto", models.CharField(max_length=15)),
                ("ValorSistema", models.CharField(default="N", max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "ClaveSHCPImpuesto",
                    models.ForeignKey(
                        db_column="ClaveSHCPImpuesto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clavesSHCPImpuestos",
                        to="store.catalogos",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaImpuestos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioImpuestos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuestos",
                "db_table": "Impuesto",
                "ordering": ("-IdImpuesto",),
            },
        ),
        migrations.CreateModel(
            name="ImpuestoTasas",
            fields=[
                ("IdTasaImpuesto", models.IntegerField(db_index=True, unique=True)),
                ("TasaImpuesto", models.DecimalField(decimal_places=4, max_digits=11)),
                ("EtiquetaImpuesto", models.CharField(max_length=15)),
                ("BaseCalculoImpuesto", models.CharField(max_length=1)),
                ("ClaseImpuesto", models.CharField(max_length=1)),
                ("OrdenImpuesto", models.IntegerField()),
                ("TipoFactorSATImpuesto", models.CharField(max_length=1)),
                (
                    "IdElementoTasaImpuesto",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("ValorSistema", models.CharField(default="N", max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "IdImpuesto",
                    models.ForeignKey(
                        db_column="IdImpuesto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impuestosTasas",
                        to="store.impuestos",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaImpuestoTasas",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioImpuestoTasas",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "ImpuestoTasa",
                "verbose_name_plural": "ImpuestoTasas",
                "db_table": "ImpuestoTasas",
                "ordering": ("-IdImpuesto",),
                "unique_together": {("IdImpuesto", "IdTasaImpuesto")},
                "index_together": {("IdImpuesto", "IdTasaImpuesto")},
            },
        ),
        migrations.CreateModel(
            name="ListasPrecios",
            fields=[
                (
                    "IdListaPrecio",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("DescripcionListaPrecio", models.CharField(max_length=40)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaListasPrecios",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioListasPrecios",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "ListaPrecio",
                "verbose_name_plural": "ListasPrecios",
                "db_table": "ListasPrecios",
                "ordering": ("-IdListaPrecio",),
            },
        ),
        migrations.CreateModel(
            name="ListaPreciosArticulos",
            fields=[
                ("FechaInicioPrecio", models.DateField(db_index=True)),
                ("HoraInicioPrecio", models.TimeField(db_index=True)),
                (
                    "PrecioArticulo",
                    models.DecimalField(decimal_places=6, max_digits=22),
                ),
                (
                    "IdElementoPrecioArticulo",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "DivisaPrecioArticulo",
                    models.ForeignKey(
                        db_column="DivisaPrecioArticulo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="divisasListasPrecios",
                        to="store.divisas",
                        to_field="IdDivisa",
                    ),
                ),
                (
                    "IdArticulo",
                    models.ForeignKey(
                        db_column="IdArticulo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulosListasPreciosArticulos",
                        to="store.articulos",
                        to_field="IdArticulo",
                    ),
                ),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        db_column="IdCategoria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categoriasListasPreciosArticulos",
                        to="store.categoriasarticulos",
                        to_field="IdCategoria",
                    ),
                ),
                (
                    "IdListaPrecio",
                    models.ForeignKey(
                        db_column="IdListaPrecio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listasPreciosArticulos",
                        to="store.listasprecios",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaListaPreciosArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioListaPreciosArticulos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "ListaPreciosArticulos",
                "verbose_name_plural": "ListasPreciosArticulos",
                "db_table": "ListaPreciosArticulos",
                "ordering": ("-IdListaPrecio",),
                "unique_together": {
                    (
                        "IdListaPrecio",
                        "IdCategoria",
                        "IdArticulo",
                        "FechaInicioPrecio",
                        "HoraInicioPrecio",
                    )
                },
                "index_together": {
                    (
                        "IdListaPrecio",
                        "IdCategoria",
                        "IdArticulo",
                        "FechaInicioPrecio",
                        "HoraInicioPrecio",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="ListaPreciosArticuloImpuestos",
            fields=[
                ("FechaInicioPrecio", models.DateField(db_index=True)),
                ("HoraInicioPrecio", models.TimeField(db_index=True)),
                ("BaseCalculoImpuestoPrecio", models.CharField(max_length=1)),
                (
                    "IdElementoImpuestoPrecio",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "IdArticulo",
                    models.ForeignKey(
                        db_column="IdArticulo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulosListasPreciosArticulosImpuestos",
                        to="store.articulos",
                        to_field="IdArticulo",
                    ),
                ),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        db_column="IdCategoria",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categoriasListasPreciosArticuloImpuestos",
                        to="store.categoriasarticulos",
                        to_field="IdCategoria",
                    ),
                ),
                (
                    "IdListaPrecio",
                    models.ForeignKey(
                        db_column="IdListaPrecio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listasPreciosArticulosImpuestos",
                        to="store.listasprecios",
                    ),
                ),
                (
                    "TasaImpuestoPrecio",
                    models.ForeignKey(
                        db_column="TasaImpuestoPrecio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impuestosTasasListasPrecios",
                        to="store.impuestotasas",
                        to_field="IdTasaImpuesto",
                    ),
                ),
                (
                    "TipoImpuestoPrecio",
                    models.ForeignKey(
                        db_column="TipoImpuestoPrecio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impuestosListasPrecios",
                        to="store.impuestos",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaListaPreciosArticuloImpuestos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioListaPreciosArticuloImpuestos",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "ZonaImpuestoPrecio",
                    models.ForeignKey(
                        db_column="ZonaImpuestoPrecio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zonasImpuestosListasPrecios",
                        to="store.catalogos",
                    ),
                ),
            ],
            options={
                "verbose_name": "ListaPreciosArticulos",
                "verbose_name_plural": "ListasPreciosArticulos",
                "db_table": "ListaPreciosArticuloImpuestos",
                "ordering": ("-IdListaPrecio",),
                "unique_together": {
                    (
                        "IdListaPrecio",
                        "IdCategoria",
                        "IdArticulo",
                        "FechaInicioPrecio",
                        "HoraInicioPrecio",
                    )
                },
                "index_together": {
                    (
                        "IdListaPrecio",
                        "IdCategoria",
                        "IdArticulo",
                        "FechaInicioPrecio",
                        "HoraInicioPrecio",
                    )
                },
            },
        ),
    ]
