# Generated by Django 4.2.8 on 2024-06-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_impuestos_impuestotasas_listasprecios_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="impuestos",
            options={
                "ordering": ("-IdImpuesto",),
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
            },
        ),
        migrations.AlterModelOptions(
            name="listapreciosarticuloimpuestos",
            options={
                "ordering": ("-IdListaPrecio",),
                "verbose_name": "ListaPreciosArticulosImpuestos",
                "verbose_name_plural": "ListasPreciosArticulosImpuestos",
            },
        ),
        migrations.AddField(
            model_name="impuestotasas",
            name="BaseImpuesto",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=22),
        ),
    ]
