# Generated by Django 4.2.8 on 2024-06-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_alter_impuestos_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo01",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo02",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo03",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo04",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo05",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo06",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo07",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo08",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo09",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo10",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo11",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EntradasExistenciasArticulo12",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="InicialExistenciasArticulo",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo01",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo02",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo03",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo04",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo05",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo06",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo07",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo08",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo09",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo10",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo11",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="SalidasExistenciasArticulo12",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
    ]
