# Generated by Django 4.2.8 on 2024-06-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_empleados_departamentoempleado_and_more"),
        (
            "store",
            "0018_alter_almacenarticuloexistencias_entradasexistenciasarticulo01_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="EstadoLogico",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaExistencias",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioExistencias",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="almacenarticuloexistencias",
            name="Version",
            field=models.IntegerField(default=0),
        ),
    ]
