# Generated by Django 4.2.8 on 2024-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0019_alter_almacenarticuloexistencias_estadologico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulos",
            name="DescripcionArticulo",
            field=models.CharField(max_length=1026),
        ),
    ]
