<<<<<<< HEAD
# Generated by Django 4.2.8 on 2025-04-25 02:46
=======
# Generated by Django 4.2.8 on 2025-04-25 01:13
>>>>>>> heroku

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_alter_articulos_descripcionarticulo"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="almacenarticuloexistencias",
            table="almacenarticuloexistencias",
        ),
        migrations.AlterModelTable(
            name="almacenarticulos",
            table="almacenarticulos",
        ),
        migrations.AlterModelTable(
            name="almacenes",
            table="almacenes",
        ),
        migrations.AlterModelTable(
            name="articulos",
            table="articulos",
        ),
        migrations.AlterModelTable(
            name="catalogos",
            table="catalogos",
        ),
        migrations.AlterModelTable(
            name="categoriasarticulos",
            table="categoriasarticulos",
        ),
        migrations.AlterModelTable(
            name="clientes",
            table="clientes",
        ),
        migrations.AlterModelTable(
            name="condicionespago",
            table="condicionespago",
        ),
        migrations.AlterModelTable(
            name="costosarticulos",
            table="costosarticulos",
        ),
        migrations.AlterModelTable(
            name="divisas",
            table="divisas",
        ),
        migrations.AlterModelTable(
            name="impuestos",
            table="impuestos",
        ),
        migrations.AlterModelTable(
            name="impuestotasas",
<<<<<<< HEAD
            table="impuestostasas",
        ),
        migrations.AlterModelTable(
            name="listapreciosarticuloimpuestos",
            table="listapreciosarticuloimpuestos",
=======
            table="impuestotasas",
        ),
        migrations.AlterModelTable(
            name="listapreciosarticuloimpuestos",
            table="listapreciosarticuloImpuestos",
>>>>>>> heroku
        ),
        migrations.AlterModelTable(
            name="listapreciosarticulos",
            table="listapreciosarticulos",
        ),
        migrations.AlterModelTable(
            name="listasprecios",
            table="listasprecios",
        ),
        migrations.AlterModelTable(
            name="marcasarticulos",
            table="marcasarticulos",
        ),
        migrations.AlterModelTable(
            name="marcascategorias",
            table="marcascategorias",
        ),
        migrations.AlterModelTable(
            name="presentacionesarticulos",
            table="presentacionesarticulos",
        ),
        migrations.AlterModelTable(
            name="presentacionescategorias",
            table="presentacionescategorias",
        ),
        migrations.AlterModelTable(
            name="productossat",
            table="productossat",
        ),
        migrations.AlterModelTable(
            name="proveedores",
            table="proveedores",
        ),
        migrations.AlterModelTable(
            name="unidadessat",
            table="unidadessat",
        ),
    ]
