# Generated by Django 4.2.8 on 2025-04-25 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0021_alter_almacenarticuloexistencias_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productossat",
            options={
                "ordering": ("-IdProductoSAT",),
                "verbose_name": "ProductoSAT",
                "verbose_name_plural": "ProductosSAT",
            },
        ),
    ]
