# Generated by Django 4.2.8 on 2025-04-25 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0022_alter_productossat_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="impuestotasas",
            table="impuestotasas",
        ),
    ]
