# Generated by Django 4.2.8 on 2024-06-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleados",
            fields=[
                ("IdEmpleado", models.IntegerField(db_index=True)),
                ("NombreEmpleado", models.CharField(max_length=30)),
                ("ApellidoPaternoEmpleado", models.CharField(max_length=30)),
                ("ApellidoMaternoEmpleado", models.CharField(max_length=30)),
                ("DepartamentoEmpleado", models.CharField(max_length=50, null=True)),
                ("PuestoEmpleado", models.CharField(max_length=50, null=True)),
                ("FechaIngresoEmpleado", models.DateField(null=True)),
                ("FechaSalidaEmpleado", models.DateField(null=True)),
                ("RFCEmpleado", models.CharField(max_length=13, null=True)),
                (
                    "SueldoBaseEmpleado",
                    models.DecimalField(decimal_places=6, max_digits=22),
                ),
                (
                    "ComisionVentaEmpleado",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "ComisionCobranzaEmpleado",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "ImagenEmpleado",
                    models.ImageField(
                        blank=True, null=True, upload_to="empleados/%Y/%m/%d"
                    ),
                ),
                ("FormatoImagenEmpleado", models.CharField(max_length=50, null=True)),
                ("NombreImagenEmpleado", models.CharField(max_length=128, null=True)),
                (
                    "IdElementoEmpleado",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("IdUsuario", models.CharField(db_index=True, max_length=10)),
                (
                    "CredencialUsuario",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("NombreUsuario", models.CharField(max_length=30)),
                ("ApellidoPaternoUsuario", models.CharField(max_length=30)),
                ("ApellidoMaternoUsuario", models.CharField(max_length=30)),
                ("CuentaCorreoUsuario", models.CharField(max_length=100)),
                ("GrupoUsuario", models.CharField(max_length=30)),
                (
                    "ImagenUsuario",
                    models.ImageField(
                        blank=True, null=True, upload_to="usuarios/%Y/%m/%d"
                    ),
                ),
                ("FormatoImagenUsuario", models.CharField(max_length=50, null=True)),
                ("NombreImagenUsuario", models.CharField(max_length=128, null=True)),
                (
                    "LimiteConsumosUsuario",
                    models.DecimalField(decimal_places=6, max_digits=24),
                ),
                (
                    "LimiteAutorizaConsumosUsuario",
                    models.DecimalField(decimal_places=6, max_digits=24),
                ),
                (
                    "LimiteComprasUsuario",
                    models.DecimalField(decimal_places=6, max_digits=24),
                ),
                (
                    "LimiteAutorizaComprasUsuario",
                    models.DecimalField(decimal_places=6, max_digits=24),
                ),
                (
                    "LimiteAutorizaPagosUsuario",
                    models.DecimalField(decimal_places=6, max_digits=24),
                ),
                (
                    "LimiteAutorizaVentaUsuario",
                    models.DecimalField(decimal_places=6, max_digits=24),
                ),
                (
                    "PorcentajeMaximoVentaUsuario",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("NivelAutorizacionUsuario", models.CharField(max_length=1)),
                (
                    "IdElementoUsuario",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField()),
                ("Version", models.IntegerField()),
                (
                    "IdEmpleado",
                    models.OneToOneField(
                        db_column="IdEmpleado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.empleados",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaUsuarios",
                        to="website.usuarios",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioUsuarios",
                        to="website.usuarios",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empleados",
            name="UsuarioAlta",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaEmpleados",
                to="website.usuarios",
            ),
        ),
        migrations.AddField(
            model_name="empleados",
            name="UsuarioCambio",
            field=models.ForeignKey(
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioEmpleados",
                to="website.usuarios",
            ),
        ),
    ]
