# Generated by Django 4.2.8 on 2024-06-08 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empleados",
            options={
                "ordering": ("-IdEmpleado",),
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
        migrations.AlterModelOptions(
            name="usuarios",
            options={
                "ordering": ("-IdUsuario",),
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AlterModelTable(
            name="empleados",
            table="Empleados",
        ),
        migrations.AlterModelTable(
            name="usuarios",
            table="Usuarios",
        ),
    ]
