# Generated by Django 4.2.8 on 2024-06-08 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_empleados_options_alter_usuarios_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleados",
            name="UsuarioAlta",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaEmpleados",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="UsuarioCambio",
            field=models.ForeignKey(
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioEmpleados",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="IdUsuario",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="UsuarioAlta",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaUsuarios",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="UsuarioCambio",
            field=models.ForeignKey(
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioUsuarios",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
    ]
