# Generated by Django 4.2.8 on 2024-06-09 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_empleados_usuarioalta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="IdEmpleado",
        ),
        migrations.AddField(
            model_name="empleados",
            name="IdUsuario",
            field=models.OneToOneField(
                db_column="IdUsuario",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.usuarios",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="empleados",
            unique_together={("IdEmpleado", "IdUsuario")},
        ),
        migrations.AlterIndexTogether(
            name="empleados",
            index_together={("IdEmpleado", "IdUsuario")},
        ),
    ]
