# Generated by Django 4.2.8 on 2024-06-27 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_usuarios_idempleado_empleados_idusuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleados",
            name="DepartamentoEmpleado",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="EstadoLogico",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="FechaIngresoEmpleado",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="FechaSalidaEmpleado",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="FormatoImagenEmpleado",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="NombreImagenEmpleado",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="PuestoEmpleado",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="RFCEmpleado",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaEmpleados",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioEmpleados",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="empleados",
            name="Version",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="EstadoLogico",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="FormatoImagenUsuario",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="NombreImagenUsuario",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaUsuarios",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioUsuarios",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="Version",
            field=models.IntegerField(default=0),
        ),
    ]
