# Generated by Django 4.2.8 on 2025-04-25 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_empleados_departamentoempleado_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="empleados",
            table="empleados",
        ),
        migrations.AlterModelTable(
            name="usuarios",
            table="usuarios",
        ),
    ]
