# Generated by Django 4.2.8 on 2024-07-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("website", "0005_alter_empleados_departamentoempleado_and_more"),
        ("store", "0020_alter_articulos_descripcionarticulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigosPostales",
            fields=[
                ("IdCodigoPostal", models.IntegerField(db_index=True, unique=True)),
                (
                    "IdElementoCodigoPostal",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("ValorSistema", models.CharField(max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "CodigoPostal",
                "verbose_name_plural": "CodigosPostales",
                "db_table": "CodigosPostales",
                "ordering": ("-IdCodigoPostal",),
            },
        ),
        migrations.CreateModel(
            name="Colonias",
            fields=[
                ("IdColonia", models.IntegerField(db_index=True)),
                ("NombreColonia", models.CharField(max_length=60)),
                ("ValorSistema", models.CharField(max_length=1)),
                (
                    "IdElementoColonia",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "IdCodigoPostal",
                    models.ForeignKey(
                        db_column="IdCodigoPostal",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cpColonias",
                        to="orders.codigospostales",
                        to_field="IdCodigoPostal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colonia",
                "verbose_name_plural": "Colonias",
                "db_table": "Colonias",
                "ordering": ("-IdColonia",),
            },
        ),
        migrations.CreateModel(
            name="ContactoMedios",
            fields=[
                (
                    "IdContactoMedio",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("DatoTipoMedioContacto", models.CharField(max_length=64)),
                ("PrimarioMedioContacto", models.CharField(max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "TipoMedioContacto",
                    models.ForeignKey(
                        db_column="TipoMedioContacto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tiposMediosContactoMedios",
                        to="store.catalogos",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaContactoMedios",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioContactoMedios",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioContactoMedio",
                    models.ForeignKey(
                        db_column="UsuarioContactoMedio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuariosContactoMedios",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "ContactoMedio",
                "verbose_name_plural": "ContactoMedios",
                "db_table": "ContactoMedios",
                "unique_together": {("UsuarioContactoMedio", "TipoMedioContacto")},
                "index_together": {("UsuarioContactoMedio", "TipoMedioContacto")},
            },
        ),
        migrations.CreateModel(
            name="EntidadesFederativas",
            fields=[
                (
                    "IdEntidadFederativa",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("NombreEntidadFederativa", models.CharField(max_length=30)),
                ("EtiquetaEntidadFederativa", models.CharField(max_length=5)),
                ("HusoHorarioEntidadFederativa", models.IntegerField()),
                ("ValorSistema", models.CharField(max_length=1)),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaEntidadesFederativas",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioEntidadesFederativas",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "EntidadFederativa",
                "verbose_name_plural": "EntidadesFederativas",
                "db_table": "EntidadesFederativas",
                "ordering": ("-IdEntidadFederativa",),
            },
        ),
        migrations.CreateModel(
            name="Localidades",
            fields=[
                ("IdLocalidad", models.IntegerField(db_index=True)),
                ("NombreLocalidad", models.CharField(max_length=50)),
                ("ValorSistema", models.CharField(max_length=1)),
                (
                    "IdElementoLocalidad",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "IdEntidadFederativa",
                    models.ForeignKey(
                        db_column="IdEntidadFederativa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entidadesFederativasLocalidades",
                        to="orders.entidadesfederativas",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaLocalidades",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioLocalidades",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "db_table": "Localidades",
                "ordering": ("-IdLocalidad",),
                "unique_together": {("IdEntidadFederativa", "IdLocalidad")},
                "index_together": {("IdEntidadFederativa", "IdLocalidad")},
            },
        ),
        migrations.CreateModel(
            name="OrdenesCliente",
            fields=[
                ("IdOrdenCliente", models.IntegerField(db_index=True, unique=True)),
                ("NombreOrdenCliente", models.CharField(max_length=30)),
                ("ApellidoPaternoOrdenCliente", models.CharField(max_length=30)),
                (
                    "ApellidoMaternoOrdenCliente",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("DomicilioOrdenCliente", models.CharField(max_length=1023)),
                ("PagoOrdenCliente", models.BooleanField(default=False)),
                (
                    "IdElementoOrdenCliente",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("FechaAlta", models.DateField(auto_now_add=True)),
                ("HoraAlta", models.TimeField(auto_now_add=True)),
                ("FechaCambio", models.DateField(auto_now=True, null=True)),
                ("HoraCambio", models.TimeField(auto_now=True, null=True)),
                ("EstadoLogico", models.IntegerField(default=1)),
                ("Version", models.IntegerField(default=0)),
                (
                    "CodigoPostalOrdenCliente",
                    models.ForeignKey(
                        db_column="CodigoPostalOrdenCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cpOrdenesCliente",
                        to="orders.codigospostales",
                        to_field="IdCodigoPostal",
                    ),
                ),
                (
                    "ColoniaOrdenCliente",
                    models.ForeignKey(
                        db_column="ColoniaOrdenCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coloniasOrdenesCliente",
                        to="orders.colonias",
                    ),
                ),
                (
                    "CorreoElectronicoOrdenCliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="CorreoElectronicoOrdenCliente",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correosOrdenesCliente",
                        to="orders.contactomedios",
                    ),
                ),
                (
                    "EntidadFederativaOrdenCliente",
                    models.ForeignKey(
                        db_column="EntidadFederativaOrdenCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entidadesFederativasOrdenesCliente",
                        to="orders.entidadesfederativas",
                    ),
                ),
                (
                    "LocalidadOrdenCliente",
                    models.ForeignKey(
                        db_column="LocalidadOrdenCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="localidadesOrdenesCliente",
                        to="orders.localidades",
                    ),
                ),
                (
                    "NumeroTelefonicoOrdenCliente",
                    models.ForeignKey(
                        db_column="NumeroTelefonicoOrdenCliente",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telefonosOrdenesCliente",
                        to="orders.contactomedios",
                    ),
                ),
                (
                    "UsuarioAlta",
                    models.ForeignKey(
                        db_column="UsuarioAlta",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioAltaOrdenesCliente",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioCambio",
                    models.ForeignKey(
                        blank=True,
                        db_column="UsuarioCambio",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarioCambioOrdenesCliente",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
                (
                    "UsuarioOrdenCliente",
                    models.ForeignKey(
                        db_column="UsuarioOrdenCliente",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuariosOrdenesCliente",
                        to="website.usuarios",
                        to_field="IdUsuario",
                    ),
                ),
            ],
            options={
                "verbose_name": ("OrdenCliente",),
                "verbose_name_plural": "OrdenesClientes",
                "db_table": "OrdenesCliente",
                "ordering": ("-FechaAlta", "-HoraAlta", "-IdOrdenCliente"),
                "unique_together": {("IdOrdenCliente", "UsuarioOrdenCliente")},
                "index_together": {("IdOrdenCliente", "UsuarioOrdenCliente")},
            },
        ),
        migrations.CreateModel(
            name="ItemOrdenesCliente",
            fields=[
                (
                    "IdItemOrden",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "PrecioItemOrden",
                    models.DecimalField(decimal_places=6, max_digits=22),
                ),
                ("CantidadItemOrden", models.PositiveIntegerField(default=0)),
                (
                    "ArticuloItemOrden",
                    models.ForeignKey(
                        db_column="ArticuloItemOrden",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulosItemOrden",
                        to="store.articulos",
                        to_field="IdArticulo",
                    ),
                ),
                (
                    "OrdenItemOrden",
                    models.ForeignKey(
                        db_column="OrdenItemOrden",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenesItemOrden",
                        to="orders.ordenescliente",
                        to_field="IdOrdenCliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "ItemOrdenCliente",
                "verbose_name_plural": "ItemOrdenesCliente",
                "db_table": "ItemOrdenCliente",
            },
        ),
        migrations.AddField(
            model_name="colonias",
            name="IdEntidadFederativa",
            field=models.ForeignKey(
                db_column="IdEntidadFederativa",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entidadesFederativasColonias",
                to="orders.entidadesfederativas",
            ),
        ),
        migrations.AddField(
            model_name="colonias",
            name="IdLocalidad",
            field=models.ForeignKey(
                db_column="IdLocalidad",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localidadesColonias",
                to="orders.localidades",
            ),
        ),
        migrations.AddField(
            model_name="colonias",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaColonias",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AddField(
            model_name="colonias",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioColonias",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AddField(
            model_name="codigospostales",
            name="IdEntidadFederativa",
            field=models.ForeignKey(
                db_column="IdEntidadFederativa",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entidadesFederativasCP",
                to="orders.entidadesfederativas",
            ),
        ),
        migrations.AddField(
            model_name="codigospostales",
            name="IdLocalidad",
            field=models.ForeignKey(
                db_column="IdLocalidad",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localidadesCP",
                to="orders.localidades",
            ),
        ),
        migrations.AddField(
            model_name="codigospostales",
            name="UsuarioAlta",
            field=models.ForeignKey(
                db_column="UsuarioAlta",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioAltaCP",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AddField(
            model_name="codigospostales",
            name="UsuarioCambio",
            field=models.ForeignKey(
                blank=True,
                db_column="UsuarioCambio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarioCambioCP",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="colonias",
            unique_together={
                ("IdEntidadFederativa", "IdLocalidad", "IdCodigoPostal", "IdColonia")
            },
        ),
        migrations.AlterIndexTogether(
            name="colonias",
            index_together={
                ("IdEntidadFederativa", "IdLocalidad", "IdCodigoPostal", "IdColonia")
            },
        ),
        migrations.AlterUniqueTogether(
            name="codigospostales",
            unique_together={("IdEntidadFederativa", "IdLocalidad", "IdCodigoPostal")},
        ),
        migrations.AlterIndexTogether(
            name="codigospostales",
            index_together={("IdEntidadFederativa", "IdLocalidad", "IdCodigoPostal")},
        ),
    ]
