# Generated by Django 4.2.8 on 2024-11-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenescliente",
            name="CorreoElectronicoOrdenCliente",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="ordenescliente",
            name="NumeroTelefonicoOrdenCliente",
            field=models.IntegerField(),
        ),
    ]
