# Generated by Django 4.2.8 on 2024-11-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_ordenescliente_correoelectronicoordencliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenescliente",
            name="CodigoPostalOrdenCliente",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ordenescliente",
            name="ColoniaOrdenCliente",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ordenescliente",
            name="EntidadFederativaOrdenCliente",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ordenescliente",
            name="LocalidadOrdenCliente",
            field=models.CharField(max_length=200),
        ),
    ]
