# Generated by Django 4.2.8 on 2024-11-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_ordenescliente_codigopostalordencliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenescliente",
            name="NumeroTelefonicoOrdenCliente",
            field=models.CharField(max_length=10),
        ),
    ]
