# Generated by Django 4.2.8 on 2024-11-08 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_empleados_departamentoempleado_and_more"),
        ("orders", "0004_alter_ordenescliente_numerotelefonicoordencliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenescliente",
            name="UsuarioOrdenCliente",
            field=models.ForeignKey(
                db_column="UsuarioOrdenCliente",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuariosOrdenesCliente",
                to="website.usuarios",
                to_field="IdUsuario",
            ),
        ),
    ]
