# Generated by Django 4.2.8 on 2025-04-25 01:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_ordenescliente_usuarioordencliente"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="codigospostales",
            table="codigospostales",
        ),
        migrations.AlterModelTable(
            name="colonias",
            table="colonias",
        ),
        migrations.AlterModelTable(
            name="contactomedios",
            table="contactomedios",
        ),
        migrations.AlterModelTable(
            name="entidadesfederativas",
            table="entidadesfederativas",
        ),
        migrations.AlterModelTable(
            name="itemordenescliente",
            table="itemordencliente",
        ),
        migrations.AlterModelTable(
            name="localidades",
            table="localidades",
        ),
        migrations.AlterModelTable(
            name="ordenescliente",
            table="ordenescliente",
        ),
    ]
